name: build-and-test

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup C++ environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake

      - name: Configure CMake
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --parallel 4

      - name: Run Tests
        run: |
          cd build/tests
          ./test_core
          ./test_tsp
          ./test_operators

  # Optional: Check lefthook config is valid
  lefthook-check:
    name: Lefthook Config Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install lefthook
        run: |
          curl -L -o lefthook https://github.com/evilmartians/lefthook/releases/latest/download/lefthook_linux_amd64
          chmod +x lefthook
          sudo mv lefthook /usr/local/bin/

      - name: Validate lefthook config
        run: lefthook dump
